server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: auth-service

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver

# JWT token expiry (shared across profiles)
netserve:
  jwt:
    access-token-expiry: 3600000 # 1 hour
    refresh-token-expiry: 604800000 # 7 days
  app:
    from-email: noreply@netserve.io
